# Generated by Django 6.1 on 2026-08-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad  dir stock\\migrations asistentes'),
        ),
    ]
