# Generated by Django 6.1 on 2026-08-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_evento_hora_inicio_evento_asistentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=12),
        ),
        migrations.AddField(
            model_name='evento',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='asistentes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de asistentes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='stock.menu'),
        ),
        migrations.AddField(
            model_name='evento',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='stock.paquete'),
        ),
    ]
