# Generated by Django 6.1 on 2026-08-13 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_menu_paquete_evento_estado_evento_telefono_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='motivo',
            field=models.CharField(blank=True, choices=[('rotura', 'Rotura'), ('vencimiento', 'Vencimiento'), ('consumo_interno', 'Consumo interno'), ('otro', 'Otro')], default='', help_text='Solo para las mermas: por qué se perdió la mercadería.', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuando el stock llegue a este valor, el producto se marca para reponer. 0 = sin aviso.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('merma', 'Merma')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
