# Generated by Django 6.1 on 2026-08-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_movimientostock_motivo_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
