# Generated by Django 6.1 on 2026-08-13 14:08

import django.core.validators
from django.db import migrations, models


def sellar_costo_de_los_movimientos_viejos(apps, schema_editor):
    """Le pone a cada movimiento existente el precio ACTUAL de su producto.

    Es una aproximación, y hay que saberlo: el costo real del momento nunca se
    guardó, así que no hay forma de reconstruirlo. Estos movimientos quedan
    valuados a precios de hoy. De acá en adelante el costo se sella al crear
    cada movimiento y el número sí es fiel.
    """
    MovimientoStock = apps.get_model('stock', 'MovimientoStock')
    for movimiento in MovimientoStock.objects.select_related('producto'):
        movimiento.costo_unitario = movimiento.producto.precio_unitario
        movimiento.save(update_fields=['costo_unitario'])


def desellar(apps, schema_editor):
    """Marcha atrás: el campo se va con el RemoveField, no hay nada que deshacer."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='reabierto_el',
            field=models.DateTimeField(blank=True, help_text='Queda marcado si el evento se reabrió después de haberse cerrado.', null=True, verbose_name='Reabierto el'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que valía el producto cuando se registró el movimiento. Se sella solo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario'),
        ),
        migrations.RunPython(sellar_costo_de_los_movimientos_viejos, desellar),
    ]
