# Generated by Django 6.1 on 2026-08-13 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_evento_reabierto_el_movimientostock_costo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_cerrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total acordado. Si lo cargás, manda sobre el precio por persona.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio cerrado'),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_por_persona',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que se cobra por cubierto. Se multiplica por los asistentes.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por persona'),
        ),
        migrations.CreateModel(
            name='CargoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej. Barra libre, DJ, hora extra.', max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='stock.evento')),
            ],
            options={
                'verbose_name': 'Cargo al cliente',
                'verbose_name_plural': 'Cargos al cliente',
            },
        ),
    ]
