# Generated by Django 6.1 on 2026-08-13 14:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_evento_precio_cerrado_evento_precio_por_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_persona', models.DecimalField(decimal_places=3, help_text='Ej. 0,200 para 200 g de carne por cubierto.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad por persona')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='stock.evento')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='stock.menu')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_recetas', to='stock.producto')),
            ],
            options={
                'verbose_name': 'Línea de receta',
                'verbose_name_plural': 'Líneas de receta',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('evento__isnull', True), ('menu__isnull', False)), models.Q(('evento__isnull', False), ('menu__isnull', True)), _connector='OR'), name='linea_receta_tiene_un_solo_dueno', violation_error_message='Una línea de receta pertenece a un menú o a un evento, no a los dos.')],
            },
        ),
    ]
