# Generated by Django 6.1 on 2026-08-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_lineareceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Los productos dados de baja no aparecen en Compras, Consumo ni Merma, pero conservan su historial.'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stock.producto'),
        ),
    ]
