# Generated by Django 6.1 on 2026-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_puesto_plato_receta_por_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sector',
            field=models.CharField(choices=[('barra', 'Barra'), ('cocina', 'Cocina'), ('extras', 'Extras'), ('limpieza', 'Limpieza'), ('mobiliario', 'Mobiliario')], max_length=20),
        ),
    ]
