# Generated by Django 6.1 on 2026-08-14 00:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_sectores_limpieza_y_mobiliario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='brindis_asistentes',
            field=models.PositiveIntegerField(blank=True, help_text='Cuántos participan del brindis. No siempre son todos los invitados.', null=True, verbose_name='Asistentes al brindis'),
        ),
        migrations.AddField(
            model_name='evento',
            name='brindis_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que se cobra por persona por el brindis.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del brindis'),
        ),
        migrations.CreateModel(
            name='TarjetaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej. Adultos, Menú infantil, Músicos.', max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad de tarjetas')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de la tarjeta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='stock.evento')),
                ('menu', models.ForeignKey(blank=True, help_text='Qué come este grupo. Si lo cargás, la receta se calcula para esta cantidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to='stock.menu')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['-cantidad', 'concepto'],
            },
        ),
    ]
