# Generated by Django 6.1 on 2026-08-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_tarjetas_y_brindis'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='porciones',
            field=models.PositiveIntegerField(blank=True, help_text='Para cuántas personas sale este plato. Lo completa la tarjeta.', null=True),
        ),
    ]
