# Generated by Django 6.1 on 2026-08-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_sellar_precio_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombre', models.CharField(blank=True, help_text='Opcional, para saber quién es.', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Destildalo para dejar de avisarle sin borrarlo.')),
            ],
            options={
                'verbose_name': 'Destinatario de avisos',
                'verbose_name_plural': 'Destinatarios de avisos',
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='aviso_enviado_el',
            field=models.DateTimeField(blank=True, help_text='Cuándo salió el recordatorio por mail. Vaciálo para que se vuelva a mandar.', null=True, verbose_name='Aviso enviado el'),
        ),
    ]
