# Generated by Django 6.1 on 2026-08-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_avisos_por_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='precio_cerrado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='precio_por_persona',
        ),
    ]
