"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo usa la clave de siempre; en el servidor definir DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-yhmo_cjge!e&)=v(y%sxfrtnbw5psvy%iek@w4rc%$r=m0xu^+',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Sigue en True por defecto para no romper el runserver local: en el servidor
# definir DJANGO_DEBUG=False.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# Hosts permitidos, separados por coma. El default cubre el desarrollo local y
# el cliente de tests; en el servidor definir DJANGO_ALLOWED_HOSTS.
#
# En produccion (ejemplo, PowerShell):
#   $env:DJANGO_SECRET_KEY    = "<clave larga y secreta>"
#   $env:DJANGO_DEBUG         = "False"
#   $env:DJANGO_ALLOWED_HOSTS = "salonvictoria.com.ar,www.salonvictoria.com.ar"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver'
    ).split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Todo el sistema pide sesión. Una línea acá cubre las 40 vistas y las que
    # vengan; con LoginRequiredMixin habría que acordarse en cada una. La vista
    # de login y el admin quedan exentos por su cuenta.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Decide si el template se sirve entero o como fragmento de modal.
                'stock.context_processors.modal',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Autenticacion
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth
# Se usan nombres de ruta con namespace (no paths hardcodeados): resolve_url()
# los traduce, y si maniana cambia la URL no hay que tocar este archivo.

# A donde manda LoginRequiredMixin / @login_required cuando no hay sesion.
LOGIN_URL = 'stock:login'

# A donde cae el usuario despues de ingresar, si no hay ?next=.
LOGIN_REDIRECT_URL = 'stock:home'

# A donde cae el usuario despues de cerrar sesion. Sin esto, LogoutView
# renderizaria el template de deslogueo del admin, ajeno al diseno del sitio.
LOGOUT_REDIRECT_URL = 'stock:login'


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Antes esto era un diccionario llamado MAILERS, que Django ignora por completo:
# el setting real se llama EMAIL_BACKEND y es un string. Hoy el sistema no manda
# ningun mail; con el backend de consola, si algun dia se manda uno, sale por la
# terminal en vez de intentar conectarse a un SMTP inexistente.

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
